name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/bun-install@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Check Prettier formatting
        run: bun run pretty:check

      - name: Build project
        run: bun run build
